m <- Model()

m$var(x >= 0)

expect_named(x)
expect_equal(x$bounds[1], 0)
expect_equal(x$bounds[2], Inf)
expect_equal(x$name, "x")
expect_equal(x$integer, "Real")
expect_equal(capture.output(x), "x ∈ ℝ ∩ [0, Inf)")

m$var(y <= 10)
expect_named(y)
expect_equal(y$bounds[1],-Inf)
expect_equal(y$bounds[2], 10)
expect_equal(y$name, "y")
expect_equal(y$integer, "Real")
expect_equal(capture.output(y), "y ∈ ℝ ∩ (-Inf, 10]")

m$var(z)
expect_named(z)
expect_equal(z$bounds[1],-Inf)
expect_equal(z$bounds[2], Inf)
expect_equal(z$name, "z")
expect_equal(z$integer, "Real")
expect_equal(capture.output(z), "z ∈ ℝ")

m$var(a[1:10] >= 0)
expect_named(a)
expect_named(a_1)
expect_named(a_10)
expect_equal(a$bounds[1], 0)
expect_equal(a$bounds[2], Inf)
expect_equal(a$name, "a")
expect_equal(a$integer, "Real")
expect_equal(length(a$indicies), 10)
expect_equal(capture.output(a), "a[i] ∈ ℝ ∩ [0, Inf) ∀ i ∈ 1:10")

m$var(b[1:10, 1:10] >= 0)
expect_named(b)
expect_named(b_1_1)
expect_named(b_10_10)
expect_equal(b$bounds[1], 0)
expect_equal(b$bounds[2], Inf)
expect_equal(b$name, "b")
expect_equal(b$integer, "Real")
expect_equal(length(b$indicies), 100)
expect_equal(capture.output(b), "b[i] ∈ ℝ ∩ [0, Inf) ∀ i ∈ 1:10 Ⓧ 1:10")

m$var(bin, integer = "Binary")
expect_equal(bin$integer, "Binary")
expect_equal(capture.output(bin), "bin ∈ {0, 1}")

m$var(int, integer = "Integer")
expect_equal(int$integer, "Integer")
expect_equal(capture.output(int), "int ∈ ℤ")
